#!/bin/bash
#PBS -q batch
#PBS -N Weasel
#PBS -r n
#PBS -k oe
#PBS -l nodes=4:ppn=4
#PBS -l walltime=999:00:00
cd /home/s2896344/assign2/weasel
mpiexec -hostfile $PBS_NODEFILE -np 16 ga_weasel > output_weasel
